name: index_creation

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - cookiecutter
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pandoc
  - pip
  - pytest
  - python=3.9
  - pyarrow
  - pyyaml
  - scipy
  - scikit-learn
  - pip:
    - autodocsumm
    - build
    - bump2version
    - furo
    - h3>=4.0.0b2
    - nbsphinx
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - git+https://github.com/dsc/bunch
